#!/usr/bin/env bash

OUT_FILE=lib/emlua.js

# Apply Emscripten changes
patch -N -p0 < emlua.patch

# Build the Lua source with Emscripten
cd lua
emmake make generic
cd ..

# Convert the output JS to an NPM module
mkdir -p `dirname $OUT_FILE`
echo 'module.exports = (function(){' > $OUT_FILE
cat lua/src/emlua_shell.js >> $OUT_FILE
echo -e '\nreturn Module;}());' >> $OUT_FILE

# Remove Node.js code from the module
patch -N -p0 < remove-nodejs.patch

# Remove Emscripten changes again
patch -R -p0 < emlua.patch
